# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the sphinx-docs/ directory with Sphinx
sphinx:
  configuration: sphinx-docs/source/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: sphinx-docs/requirements.txt
