"""
Fitting functions subpackage.

Mathematical model functions and high-level fitting wrappers,
split by family: polynomials, trigonometric, inverse, special.
"""

from ._base import DataLike, Numeric

# Re-export all names so getattr(fitting_functions, name) works
from .polynomials import (
    generate_polynomial_function,
    linear_function_with_n,
    linear_function,
    quadratic_function_complete,
    quadratic_function,
    fourth_power,
    fit_linear_function_with_n,
    fit_linear_function,
    fit_quadratic_function_complete,
    fit_quadratic_function,
    fit_fourth_power,
)
from .trigonometric import (
    generate_trigonometric_function,
    sin_function,
    sin_function_with_c,
    cos_function,
    cos_function_with_c,
    sinh_function,
    cosh_function,
    tan_function,
    tan_function_with_c,
    fit_sin_function,
    fit_sin_function_with_c,
    fit_cos_function,
    fit_cos_function_with_c,
    fit_sinh_function,
    fit_cosh_function,
    fit_tan_function,
    fit_tan_function_with_c,
)
from .inverse import (
    ln_function,
    generate_inverse_function,
    inverse_function,
    inverse_square_function,
    fit_ln_function,
    fit_inverse_function,
    fit_inverse_square_function,
)
from .special import (
    fit_gaussian_function,
    fit_exponential_function,
    fit_binomial_function,
    fit_square_pulse_function,
    fit_hermite_polynomial_3,
    fit_hermite_polynomial_4,
)

__all__ = [
    'Numeric',
    'DataLike',
    'generate_polynomial_function',
    'linear_function_with_n',
    'linear_function',
    'quadratic_function_complete',
    'quadratic_function',
    'fourth_power',
    'fit_linear_function_with_n',
    'fit_linear_function',
    'fit_quadratic_function_complete',
    'fit_quadratic_function',
    'fit_fourth_power',
    'generate_trigonometric_function',
    'sin_function',
    'sin_function_with_c',
    'cos_function',
    'cos_function_with_c',
    'sinh_function',
    'cosh_function',
    'tan_function',
    'tan_function_with_c',
    'fit_sin_function',
    'fit_sin_function_with_c',
    'fit_cos_function',
    'fit_cos_function_with_c',
    'fit_sinh_function',
    'fit_cosh_function',
    'fit_tan_function',
    'fit_tan_function_with_c',
    'ln_function',
    'generate_inverse_function',
    'inverse_function',
    'inverse_square_function',
    'fit_ln_function',
    'fit_inverse_function',
    'fit_inverse_square_function',
    'fit_gaussian_function',
    'fit_exponential_function',
    'fit_binomial_function',
    'fit_square_pulse_function',
    'fit_hermite_polynomial_3',
    'fit_hermite_polynomial_4',
]
