"""Central configuration facade (single import surface)."""
# ruff: noqa: F401

from .color_utils import lighten_hex, muted_from_hex
from .constants import (
    AVAILABLE_EQUATION_TYPES,
    DATA_FILE_TYPES,
    DEFAULT_LANGUAGE,
    EQUATIONS,
    EXIT_SIGNAL,
    FORMAT_TO_FORMULA,
    FUNCTION_TO_EQUATION,
    LANGUAGE_ALIASES,
    MATH_FUNCTION_REPLACEMENTS_COMPILED,
    SUPPORTED_LANGUAGE_CODES,
    VALID_LANGUAGE_INPUTS,
    __version__,
)
from .env import (
    DEFAULT_LOG_FILE,
    DEFAULT_LOG_LEVEL,
    DONATIONS_URL,
    ENV_SCHEMA,
    get_current_env_values,
    get_env,
    get_env_from_schema,
    initialize_and_validate_config,
    write_env_file,
)
from .equation_registry import (
    EQUATION_TYPE_EXPRESSION,
    EQUATION_TYPE_PYTHON,
    clear_equation_registry_cache,
    get_equation_registry,
    load_equation_registry,
)
from .paths import (
    FILE_CONFIG,
    ensure_output_directory,
    get_output_path,
    get_project_root,
)
from .theme import (
    FONT_CONFIG,
    PLOT_CONFIG,
    SPINBOX_STYLE,
    UI_STYLE,
    apply_hover_to_children,
    configure_ttk_styles,
    get_entry_font,
    setup_fonts,
)

__all__ = [
    "lighten_hex",
    "muted_from_hex",
    "AVAILABLE_EQUATION_TYPES",
    "DATA_FILE_TYPES",
    "DEFAULT_LANGUAGE",
    "EQUATIONS",
    "EXIT_SIGNAL",
    "FORMAT_TO_FORMULA",
    "FUNCTION_TO_EQUATION",
    "LANGUAGE_ALIASES",
    "MATH_FUNCTION_REPLACEMENTS_COMPILED",
    "SUPPORTED_LANGUAGE_CODES",
    "VALID_LANGUAGE_INPUTS",
    "__version__",
    "DEFAULT_LOG_FILE",
    "DEFAULT_LOG_LEVEL",
    "DONATIONS_URL",
    "ENV_SCHEMA",
    "get_current_env_values",
    "get_env",
    "get_env_from_schema",
    "initialize_and_validate_config",
    "write_env_file",
    "EQUATION_TYPE_EXPRESSION",
    "EQUATION_TYPE_PYTHON",
    "clear_equation_registry_cache",
    "get_equation_registry",
    "load_equation_registry",
    "FILE_CONFIG",
    "ensure_output_directory",
    "get_output_path",
    "get_project_root",
    "FONT_CONFIG",
    "PLOT_CONFIG",
    "SPINBOX_STYLE",
    "UI_STYLE",
    "apply_hover_to_children",
    "configure_ttk_styles",
    "get_entry_font",
    "setup_fonts",
]
